[package]
name = "carson-tools"
version.workspace = true
edition.workspace = true

[[bin]]
name = "time"
path = "src/bin/time.rs"

[[bin]]
name = "bash"
path = "src/bin/bash.rs"

[[bin]]
name = "coreutils"
path = "src/bin/coreutils.rs"

[dependencies]
carson-shell = { path = "../carson-shell" }
serde_json.workspace = true
uu_base32 = "0.10.0"
uu_base64 = "0.10.0"
uu_basename = "0.10.0"
uu_cat = "0.10.0"
uu_cksum = "0.10.0"
uu_comm = "0.10.0"
uu_cp = "0.10.0"
uu_csplit = "0.10.0"
uu_cut = "0.10.0"
uu_date = "0.10.0"
uu_dirname = "0.10.0"
uu_expand = "0.10.0"
uu_factor = "0.10.0"
uu_fmt = "0.10.0"
uu_fold = "0.10.0"
uu_head = "0.10.0"
uu_join = "0.10.0"
uu_link = "0.10.0"
uu_ln = "0.10.0"
uu_ls = "0.10.0"
uu_md5sum = "0.10.0"
uu_mkdir = "0.10.0"
uu_mktemp = "0.10.0"
uu_mv = "0.10.0"
uu_nl = "0.10.0"
uu_numfmt = "0.10.0"
uu_od = "0.10.0"
uu_paste = "0.10.0"
uu_pathchk = "0.10.0"
uu_pr = "0.10.0"
uu_printf = "0.10.0"
uu_ptx = "0.10.0"
uu_pwd = "0.10.0"
uu_readlink = "0.10.0"
uu_realpath = "0.10.0"
uu_rm = "0.10.0"
uu_rmdir = "0.10.0"
uu_seq = "0.10.0"
uu_sha1sum = "0.10.0"
uu_sha224sum = "0.10.0"
uu_sha256sum = "0.10.0"
uu_sha384sum = "0.10.0"
uu_sha512sum = "0.10.0"
uu_shuf = "0.10.0"
uu_sort = "0.10.0"
uu_split = "0.10.0"
uu_sum = "0.10.0"
uu_tail = "0.10.0"
uu_tee = "0.10.0"
uu_touch = "0.10.0"
uu_tr = "0.10.0"
uu_truncate = "0.10.0"
uu_tsort = "0.10.0"
uu_unexpand = "0.10.0"
uu_uniq = "0.10.0"
uu_wc = "0.10.0"
uu_yes = "0.10.0"
uucore = "0.10.0"
wit-bindgen = "0.61"