[package]
name = "carson-api"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
axum = { version = "0.8", features = ["json", "query"] }
axum-extra = { version = "0.12", features = ["typed-routing", "typed-header"] }
base64 = "0.22"
carson-host.workspace = true
futures-util.workspace = true
headers = "0.4"
http-body-util = "0.1"
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
utoipa = { version = "5", features = ["axum_extras", "macros"] }
utoipa-swagger-ui = { version = "9", features = ["axum", "vendored"] }

[dev-dependencies]
toml.workspace = true
tower = { version = "0.5", features = ["util"] }

[lib]
name = "carson_api"
path = "src/lib.rs"